# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_deals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('image', models.URLField()),
                ('rating', models.FloatField()),
                ('link', models.URLField()),
                ('actual_price', models.FloatField()),
                ('discount', models.FloatField()),
                ('location', models.TextField()),
            ],
        ),
    ]
